package entity

type Supplier struct {
	ID                            int    `json:"id"`
	PartnerId                     string `json:"partner_id"`
	PartnerName                   string `json:"partner_name"`
	CustomerId                    string `json:"customer_id"`
	CustomerName                  string `json:"customer_name"`
	CustomerDomainName            string `json:"customer_domain_name"`
	CustomerCountry               string `json:"customer_country"`
	MpnId                         string `json:"mpn_id"`
	Tier2MpnId                    string `json:"tier2_mpn_id"`
	InvoiceNumber                 string `json:"invoice_number"`
	ProductId                     string `json:"product_id"`
	SkuId                         string `json:"sku_id"`
	AvailabilityId                string `json:"availability_id"`
	SkuName                       string `json:"sku_name"`
	ProductName                   string `json:"product_name"`
	PublisherName                 string `json:"publisher_name"`
	PublisherId                   string `json:"publisher_id"`
	SubscriptionDescription       string `json:"subscription_description"`
	SubscriptionId                string `json:"subscription_id"`
	ChargeStartDate               string `json:"charge_start_date"`
	ChargeEndDate                 string `json:"charge_end_date"`
	UsageDate                     string `json:"usage_date"`
	MeterType                     string `json:"meter_type"`
	MeterCategory                 string `json:"meter_category"`
	MeterId                       string `json:"meter_id"`
	MeterSubCategory              string `json:"meter_sub_category"`
	MeterName                     string `json:"meter_name"`
	MeterRegion                   string `json:"meter_region"`
	Unit                          string `json:"unit"`
	ResourceLocation              string `json:"resource_location"`
	ConsumedService               string `json:"consumed_service"`
	ResourceGroup                 string `json:"resource_group"`
	ResourceURI                   string `json:"resource_uri"`
	ChargeType                    string `json:"charge_type"`
	UnitPrice                     string `json:"unit_price"`
	Quantity                      string `json:"quantity"`
	UnitType                      string `json:"unit_type"`
	BillingPreTaxTotal            string `json:"billing_pre_tax_total"`
	BillingCurrency               string `json:"billing_currency"`
	PricingPreTaxTotal            string `json:"pricing_pre_tax_total"`
	PricingCurrency               string `json:"pricing_currency"`
	ServiceInfo1                  string `json:"service_info1"`
	ServiceInfo2                  string `json:"service_info2"`
	Tags                          string `json:"tags"`
	AdditionalInfo                string `json:"additional_info"`
	EffectiveUnitPrice            string `json:"effective_unit_price"`
	PcToBcExchangeRate            string `json:"pc_to_bc_exchange_rate"`
	PcToBcExchangeRateDate        string `json:"pc_to_bc_exchange_rate_date"`
	EntilementId                  string `json:"entilement_id"`
	EntilementDescription         string `json:"entilement_description"`
	PartnerEarnedCreditPercentage string `json:"partner_earned_credit_percentage"`
	CreditPercentage              string `json:"credit_percentage"`
	CreditType                    string `json:"credit_type"`
	BenefitOrdertId               string `json:"benefit_ordert_id"`
	BenefitId                     string `json:"benefit_id"`
	BenefitType                   string `json:"benefit_type"`
}
